site_name: OAI private 5G Docs
site_url:  https://lrt-ligm.github.io/OAI-Private-Network
repo_url: https://github.com/LRT-LIGM/OAI-Private-Network
repo_name: GitHub

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Installation: installation.md
  - Lancement: lancement.md
  - USRP: usrp_sdr.md
  - Les Commandes:
      - QMI Commands: qmi_commands.md
      - AT Commandes: at_commands_reference.md
      - SQL Commands: docker_mysql_oai_commands.md
  - Tests: 
      - Log gNodeB: softmodem_log_success.md
      - Programmation De La Carte SIM: sim_programming_success.md
  - Uicc SIM: uicc_sim_commands.md
  - Troubleshooting : 
      - PDU Session Conflict : pdu_session_conflict.md
  - Rapport Hebdo:
      - Week 25:
          - OAI 5G SA (17 juin): week_25/weekly_reports/weekly_reports_2025_06_17.md
          - srsRAN 4G (17 juin): week_25/srsran/srs_ran_4_g_setup_report.md
          - Architecture OAI 5G SA: week_25/archi/architecture_oai_5_g_sa.md
          - SIM Programming: week_25/sim_card/sim_programming.md
          - System Reinstall (June 2025): week_25/reinstall/system_reinstall_june_2025.md
      - Week 26:
          - 01 - Modem Configuration: week_26/01_modem_configuration.md
          - 02 - Network Tests: week_26/02_network_tests.md
          - 03 - Tcpdump Analysis: week_26/03_tcpdump_analysis.md
          - 04 - Core Network Status: week_26/04_core_network_status.md
          - 05 - Ext-DN Debug: week_26/05_ext_dn_debug.md
          - 06 - Debug Investigations: week_26/06_debug_investigations.md
      - Week 27:
          - 01 - Index: week_27/index.md
          - 02 - Configuration: week_27/configuration.md
          - 03 - Installation: week_27/installation.md
          - 04 - QMI Commands: week_27/qmi_commands.md
          - 05 - Setup Core: week_27/setup_core.md
          - 06 - Setup gNodeB: week_27/setup_gnb.md
          - 07 - Tests: week_27/tests.md
      - Week 28:
          - 00 - Overview: week_28/00_overview.md
          - 01 - Environment Setup: week_28/01_environment_setup.md
          - 02 - Configuration Files: week_28/02_configuration_files.md
          - 03 - Build Errors and Fixes: week_28/03_build_errors_and_fixes.md
          - 04 - Running Tests and Logs: week_28/04_running_tests_and_logs.md
          - 05 - Code Modifications: week_28/05_code_modifications.md
          - 06 - Analysis Metrics: week_28/06_analysis_metrics.md
          - FlexRIC - Layers Intro: week_28/flexric_layers_intro.md
          - FlexRIC - Metrics Explanation: week_28/flex_ric_metrics_explanation.md
          - Logs Explanation: week_28/logs_explanation.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["backend"]
  