site_name: OAI private 5G Docs
site_url:  https://lrt-ligm.github.io/OAI-Private-Network
repo_url: https://github.com/LRT-LIGM/OAI-Private-Network
repo_name: GitHub

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Installation: installation.md
  - Lancement: lancement.md
  - USRP: usrp_sdr.md
  - Les Commandes:
      - QMI Commands: qmi_commands.md
      - AT Commandes: at_commands_reference.md
      - SQL Commands: docker_mysql_oai_commands.md
  - Tests: 
      - Log gNodeB: softmodem_log_success.md
      - Programmation De La Carte SIM: sim_programming_success.md
  - Uicc SIM: uicc_sim_commands.md
  - Troubleshooting : 
      - PDU Session Conflict : pdu_session_conflict.md
  - Rapport Hebdo:
      - OAI 5G SA (17 juin): weekly_reports/2025-06-17.md
      - srsRAN 4G (17 juin): srsran/2025-06-17.md
  - Architecture:
      - OAI 5G SA: archi/oai_5g_architecture_doc.md
  - SIM:
      - Programmation Carte SIM: sim_card/doc_sim_programming.md
  - Maintenance:
      - Réinstallation Système: reinstall/reinstall_june.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["backend"]
  